# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import irish_townlands.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barony',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('osm_id', models.IntegerField(unique=True)),
                ('name_tag', models.CharField(max_length=255, db_index=True)),
                ('name_en', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_census1901_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_census1911_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_griffithsvaluation_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('alt_name', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('alt_name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('official_name_en', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('official_name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('place', models.CharField(default=None, max_length=255, null=True)),
                ('area_m2', models.FloatField(db_index=True)),
                ('water_area_m2', models.FloatField(null=True, blank=True)),
                ('url_path', models.CharField(max_length=255, db_index=True)),
                ('unique_suffix', models.PositiveSmallIntegerField(null=True)),
                ('source', models.CharField(default=None, max_length=255, null=True)),
                ('attribution', models.CharField(default=None, max_length=255, null=True)),
                ('ref', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('centre_x', models.FloatField(default=0)),
                ('centre_y', models.FloatField(default=0)),
                ('bbox_width', models.FloatField(default=0)),
                ('bbox_height', models.FloatField(default=0)),
                ('osm_user', models.CharField(max_length=100, null=True, db_index=True)),
                ('osm_uid', models.IntegerField(null=True)),
                ('osm_timestamp', models.DateTimeField(null=True, db_index=True)),
                ('logainm_ref', models.CharField(default=None, max_length=255, null=True, db_index=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, irish_townlands.models.NameableThing),
        ),
        migrations.CreateModel(
            name='CivilParish',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('osm_id', models.IntegerField(unique=True)),
                ('name_tag', models.CharField(max_length=255, db_index=True)),
                ('name_en', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_census1901_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_census1911_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_griffithsvaluation_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('alt_name', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('alt_name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('official_name_en', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('official_name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('place', models.CharField(default=None, max_length=255, null=True)),
                ('area_m2', models.FloatField(db_index=True)),
                ('water_area_m2', models.FloatField(null=True, blank=True)),
                ('url_path', models.CharField(max_length=255, db_index=True)),
                ('unique_suffix', models.PositiveSmallIntegerField(null=True)),
                ('source', models.CharField(default=None, max_length=255, null=True)),
                ('attribution', models.CharField(default=None, max_length=255, null=True)),
                ('ref', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('centre_x', models.FloatField(default=0)),
                ('centre_y', models.FloatField(default=0)),
                ('bbox_width', models.FloatField(default=0)),
                ('bbox_height', models.FloatField(default=0)),
                ('osm_user', models.CharField(max_length=100, null=True, db_index=True)),
                ('osm_uid', models.IntegerField(null=True)),
                ('osm_timestamp', models.DateTimeField(null=True, db_index=True)),
                ('logainm_ref', models.CharField(default=None, max_length=255, null=True, db_index=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, irish_townlands.models.NameableThing),
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('osm_id', models.IntegerField(unique=True)),
                ('name_tag', models.CharField(max_length=255, db_index=True)),
                ('name_en', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_census1901_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_census1911_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_griffithsvaluation_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('alt_name', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('alt_name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('official_name_en', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('official_name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('place', models.CharField(default=None, max_length=255, null=True)),
                ('area_m2', models.FloatField(db_index=True)),
                ('water_area_m2', models.FloatField(null=True, blank=True)),
                ('url_path', models.CharField(max_length=255, db_index=True)),
                ('unique_suffix', models.PositiveSmallIntegerField(null=True)),
                ('source', models.CharField(default=None, max_length=255, null=True)),
                ('attribution', models.CharField(default=None, max_length=255, null=True)),
                ('ref', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('centre_x', models.FloatField(default=0)),
                ('centre_y', models.FloatField(default=0)),
                ('bbox_width', models.FloatField(default=0)),
                ('bbox_height', models.FloatField(default=0)),
                ('osm_user', models.CharField(max_length=100, null=True, db_index=True)),
                ('osm_uid', models.IntegerField(null=True)),
                ('osm_timestamp', models.DateTimeField(null=True, db_index=True)),
                ('logainm_ref', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('polygon_townland_gaps', models.TextField(default=b'', null=True)),
                ('polygon_townland_overlaps', models.TextField(default=b'', null=True)),
                ('polygon_barony_gaps', models.TextField(default=b'', null=True)),
                ('polygon_barony_overlaps', models.TextField(default=b'', null=True)),
                ('polygon_civil_parish_gaps', models.TextField(default=b'', null=True)),
                ('polygon_civil_parish_overlaps', models.TextField(default=b'', null=True)),
                ('polygon_ed_gaps', models.TextField(default=b'', null=True)),
                ('polygon_ed_overlaps', models.TextField(default=b'', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, irish_townlands.models.NameableThing),
        ),
        migrations.CreateModel(
            name='ElectoralDivision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('osm_id', models.IntegerField(unique=True)),
                ('name_tag', models.CharField(max_length=255, db_index=True)),
                ('name_en', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_census1901_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_census1911_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_griffithsvaluation_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('alt_name', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('alt_name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('official_name_en', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('official_name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('place', models.CharField(default=None, max_length=255, null=True)),
                ('area_m2', models.FloatField(db_index=True)),
                ('water_area_m2', models.FloatField(null=True, blank=True)),
                ('url_path', models.CharField(max_length=255, db_index=True)),
                ('unique_suffix', models.PositiveSmallIntegerField(null=True)),
                ('source', models.CharField(default=None, max_length=255, null=True)),
                ('attribution', models.CharField(default=None, max_length=255, null=True)),
                ('ref', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('centre_x', models.FloatField(default=0)),
                ('centre_y', models.FloatField(default=0)),
                ('bbox_width', models.FloatField(default=0)),
                ('bbox_height', models.FloatField(default=0)),
                ('osm_user', models.CharField(max_length=100, null=True, db_index=True)),
                ('osm_uid', models.IntegerField(null=True)),
                ('osm_timestamp', models.DateTimeField(null=True, db_index=True)),
                ('logainm_ref', models.CharField(default=None, max_length=255, null=True, db_index=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, irish_townlands.models.NameableThing),
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('key', models.CharField(unique=True, max_length=50, db_index=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('osm_id', models.IntegerField()),
                ('polygon_geojson', models.TextField(default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('when', models.DateField(auto_now=True)),
                ('percent', models.FloatField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subtownland',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('osm_id', models.CharField(unique=True, max_length=50)),
                ('osm_user', models.CharField(max_length=100, null=True, db_index=True)),
                ('osm_uid', models.IntegerField(null=True)),
                ('osm_timestamp', models.DateTimeField(null=True, db_index=True)),
                ('url_path', models.CharField(max_length=255, db_index=True)),
                ('unique_suffix', models.PositiveSmallIntegerField(null=True)),
                ('name_tag', models.CharField(max_length=255, db_index=True)),
                ('name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('alt_name', models.CharField(max_length=255, null=True, db_index=True)),
                ('location_x', models.FloatField(default=0)),
                ('location_y', models.FloatField(default=0)),
                ('alt_name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_census1901_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_census1911_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_griffithsvaluation_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('logainm_ref', models.CharField(default=None, max_length=255, null=True, db_index=True)),
            ],
            bases=(models.Model, irish_townlands.models.NameableThing),
        ),
        migrations.CreateModel(
            name='Townland',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('osm_id', models.IntegerField(unique=True)),
                ('name_tag', models.CharField(max_length=255, db_index=True)),
                ('name_en', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_census1901_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_census1911_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('name_griffithsvaluation_tag', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('alt_name', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('alt_name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('official_name_en', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('official_name_ga', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('place', models.CharField(default=None, max_length=255, null=True)),
                ('area_m2', models.FloatField(db_index=True)),
                ('water_area_m2', models.FloatField(null=True, blank=True)),
                ('url_path', models.CharField(max_length=255, db_index=True)),
                ('unique_suffix', models.PositiveSmallIntegerField(null=True)),
                ('source', models.CharField(default=None, max_length=255, null=True)),
                ('attribution', models.CharField(default=None, max_length=255, null=True)),
                ('ref', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('centre_x', models.FloatField(default=0)),
                ('centre_y', models.FloatField(default=0)),
                ('bbox_width', models.FloatField(default=0)),
                ('bbox_height', models.FloatField(default=0)),
                ('osm_user', models.CharField(max_length=100, null=True, db_index=True)),
                ('osm_uid', models.IntegerField(null=True)),
                ('osm_timestamp', models.DateTimeField(null=True, db_index=True)),
                ('logainm_ref', models.CharField(default=None, max_length=255, null=True, db_index=True)),
                ('_polygon_geojson', models.ForeignKey(default=None, to='irish_townlands.Polygon', null=True)),
                ('barony', models.ForeignKey(related_name='townlands', to='irish_townlands.Barony', null=True)),
                ('civil_parish', models.ForeignKey(related_name='townlands', to='irish_townlands.CivilParish', null=True)),
                ('county', models.ForeignKey(related_name='townlands', to='irish_townlands.County', null=True)),
                ('ed', models.ForeignKey(related_name='townlands', to='irish_townlands.ElectoralDivision', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, irish_townlands.models.NameableThing),
        ),
        migrations.CreateModel(
            name='TownlandTouch',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('length_m', models.FloatField(default=0)),
                ('direction_radians', models.FloatField()),
                ('townland_a', models.ForeignKey(related_name='touching_as_a', to='irish_townlands.Townland')),
                ('townland_b', models.ForeignKey(related_name='touching_as_b', to='irish_townlands.Townland')),
            ],
        ),
        migrations.AddField(
            model_name='subtownland',
            name='townland',
            field=models.ForeignKey(related_name='subtownlands', to='irish_townlands.Townland'),
        ),
        migrations.AddField(
            model_name='electoraldivision',
            name='_polygon_geojson',
            field=models.ForeignKey(default=None, to='irish_townlands.Polygon', null=True),
        ),
        migrations.AddField(
            model_name='electoraldivision',
            name='county',
            field=models.ForeignKey(related_name='eds', default=None, to='irish_townlands.County', null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='_polygon_geojson',
            field=models.ForeignKey(default=None, to='irish_townlands.Polygon', null=True),
        ),
        migrations.AddField(
            model_name='civilparish',
            name='_polygon_geojson',
            field=models.ForeignKey(default=None, to='irish_townlands.Polygon', null=True),
        ),
        migrations.AddField(
            model_name='civilparish',
            name='counties',
            field=models.ManyToManyField(default=None, related_name='civil_parishes', null=True, to='irish_townlands.County', db_index=True),
        ),
        migrations.AddField(
            model_name='barony',
            name='_polygon_geojson',
            field=models.ForeignKey(default=None, to='irish_townlands.Polygon', null=True),
        ),
        migrations.AddField(
            model_name='barony',
            name='county',
            field=models.ForeignKey(related_name='baronies', default=None, to='irish_townlands.County', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='townlandtouch',
            unique_together=set([('townland_a', 'townland_b')]),
        ),
    ]
