# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irish_townlands', '0002_auto_20160124_1400'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE irish_townlands_subtownland ALTER COLUMN osm_id SET DATA TYPE bigint using osm_id::bigint;")
    ]
