# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irish_townlands', '0003_auto_20160320_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtownland',
            name='osm_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
