# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('irish_townlands', '0005_auto_20160320_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(choices=[(b's', b'short'), (b'm', b'medium'), (b'l', b'long')], db_index=True, default=b'l', max_length=1)),
                ('sort_key', models.CharField(db_index=True, max_length=255)),
                ('display_html', models.CharField(max_length=500)),
                ('is_irish', models.BooleanField(db_index=True, default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
