# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irish_townlands', '0006_nameentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='barony',
            name='_tags_json',
            field=models.TextField(default=b'', null=True),
        ),
        migrations.AddField(
            model_name='civilparish',
            name='_tags_json',
            field=models.TextField(default=b'', null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='_tags_json',
            field=models.TextField(default=b'', null=True),
        ),
        migrations.AddField(
            model_name='electoraldivision',
            name='_tags_json',
            field=models.TextField(default=b'', null=True),
        ),
        migrations.AddField(
            model_name='townland',
            name='_tags_json',
            field=models.TextField(default=b'', null=True),
        ),
    ]
