# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irish_townlands', '0007_auto_20161212_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtownland',
            name='_tags_json',
            field=models.TextField(default=b'', null=True),
        ),
    ]
